// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCmbCrSQol5NPsdnxwXoe_QbP9E6MXsdo',
    appId: '1:108219638152:web:3a9ce0330a56d211801a3d',
    messagingSenderId: '108219638152',
    projectId: 'bookstoreapp-da402',
    authDomain: 'bookstoreapp-da402.firebaseapp.com',
    storageBucket: 'bookstoreapp-da402.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoQ4fl8XKjbualQtbKoNPMZ5v4L4EUdg8',
    appId: '1:108219638152:android:ec77032173314f82801a3d',
    messagingSenderId: '108219638152',
    projectId: 'bookstoreapp-da402',
    storageBucket: 'bookstoreapp-da402.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAGGAN4oXVvcXvz6BoR-CYZUJRMnNpsIA',
    appId: '1:108219638152:ios:1fe8bd21b69131f5801a3d',
    messagingSenderId: '108219638152',
    projectId: 'bookstoreapp-da402',
    storageBucket: 'bookstoreapp-da402.firebasestorage.app',
    iosBundleId: 'com.example.bookstoreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAGGAN4oXVvcXvz6BoR-CYZUJRMnNpsIA',
    appId: '1:108219638152:ios:1fe8bd21b69131f5801a3d',
    messagingSenderId: '108219638152',
    projectId: 'bookstoreapp-da402',
    storageBucket: 'bookstoreapp-da402.firebasestorage.app',
    iosBundleId: 'com.example.bookstoreApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCmbCrSQol5NPsdnxwXoe_QbP9E6MXsdo',
    appId: '1:108219638152:web:c732422e96a6a5df801a3d',
    messagingSenderId: '108219638152',
    projectId: 'bookstoreapp-da402',
    authDomain: 'bookstoreapp-da402.firebaseapp.com',
    storageBucket: 'bookstoreapp-da402.firebasestorage.app',
  );
}
